"""Mock data for the 收藏夹大脑 Streamlit demo."""

from __future__ import annotations


POSTS = [
    {
        "post_id": "rent_001",
        "title": "9平米出租屋住了一年的样子",
        "cover_text": "9m2 / 不钉墙 / 慢慢变舒服",
        "content": "用床底收纳箱、窄边小推车和折叠桌，把9平米出租屋分成睡眠区、临时工位和换衣角。",
        "tags": ["出租屋", "小户型", "床底收纳"],
        "author": "小盒子住在北方",
        "save_date": "2026-04-18",
        "last_viewed_date": "2026-05-03",
        "view_after_save_count": 5,
        "theme": "租房/小空间改造",
        "subtopics": ["床底收纳", "小空间工位", "低预算软装"],
        "ai_summary": "适合先用床底空间和可移动家具，让小房间拥有基本分区。",
        "memory_phrases": ["9平米", "床底箱", "折叠桌", "出租屋分区"],
    },
    {
        "post_id": "rent_002",
        "title": "租来的房子，也想认真过生活",
        "cover_text": "低预算软装清单",
        "content": "用可拆窗帘、床品、地毯和暖光台灯改变出租屋氛围，不碰硬装也能提升生活感。",
        "tags": ["出租屋改造", "软装", "生活感"],
        "author": "米粒的房间",
        "save_date": "2026-04-20",
        "last_viewed_date": "2026-05-02",
        "view_after_save_count": 4,
        "theme": "租房/小空间改造",
        "subtopics": ["低预算软装"],
        "ai_summary": "强调可带走、可复原的软装提升，适合预算有限的租房人。",
        "memory_phrases": ["暖光台灯", "可拆窗帘", "地毯", "软装"],
    },
    {
        "post_id": "rent_003",
        "title": "小房间不打孔收纳方案",
        "cover_text": "房东不让钉墙也能上墙",
        "content": "免钉胶挂钩、伸缩杆、门后挂袋和轻量洞洞板，可以收纳包包、帽子和日用品。",
        "tags": ["不打孔", "收纳", "免钉胶"],
        "author": "不打孔研究所",
        "save_date": "2026-04-21",
        "last_viewed_date": "2026-05-06",
        "view_after_save_count": 7,
        "theme": "租房/小空间改造",
        "subtopics": ["不打孔上墙", "出租屋避坑"],
        "ai_summary": "核心是用轻量上墙工具解决小房间垂直空间不足。",
        "memory_phrases": ["免钉胶", "伸缩杆", "门后挂袋", "洞洞板"],
    },
    {
        "post_id": "rent_004",
        "title": "打工人卧室改造清单",
        "cover_text": "周末一天就能做完",
        "content": "改造从断舍离开始，再加床底箱、折叠桌、夹缝柜和桌面收纳盒，预算控制在600元以内。",
        "tags": ["卧室改造", "打工人", "低预算"],
        "author": "周末改房间",
        "save_date": "2026-04-23",
        "last_viewed_date": "2026-05-07",
        "view_after_save_count": 6,
        "theme": "租房/小空间改造",
        "subtopics": ["床底收纳", "小空间工位", "低预算软装"],
        "ai_summary": "适合作为第一轮执行清单，从收纳和临时工位开始。",
        "memory_phrases": ["600元", "夹缝柜", "折叠桌", "桌面收纳"],
    },
    {
        "post_id": "rent_005",
        "title": "洗衣机上方空间利用",
        "cover_text": "别再空着了",
        "content": "洗衣机上方用伸缩置物架、窄洞洞板和收纳篮，能放洗衣液、纸巾和护肤品，旁边还能做小护肤台。",
        "tags": ["洗衣机上方", "置物架", "小户型"],
        "author": "阿圆的阳台",
        "save_date": "2026-04-25",
        "last_viewed_date": "2026-05-08",
        "view_after_save_count": 9,
        "theme": "租房/小空间改造",
        "subtopics": ["洗衣机上方", "不打孔上墙"],
        "ai_summary": "高匹配洗衣机上方搜索，可用置物架和洞洞板做复合收纳。",
        "memory_phrases": ["洗衣机上方", "置物架", "洞洞板", "护肤台"],
    },
    {
        "post_id": "rent_006",
        "title": "床底收纳真的救命",
        "cover_text": "换季衣服终于有地方放",
        "content": "透明床底箱适合放换季衣物，被子用压缩袋，常用物品放带轮抽屉箱，拿取更方便。",
        "tags": ["床底收纳", "换季", "出租屋"],
        "author": "小鹿会整理",
        "save_date": "2026-04-26",
        "last_viewed_date": "2026-05-04",
        "view_after_save_count": 3,
        "theme": "租房/小空间改造",
        "subtopics": ["床底收纳"],
        "ai_summary": "床底是低成本、低风险、马上见效的收纳入口。",
        "memory_phrases": ["透明床底箱", "压缩袋", "带轮抽屉"],
    },
    {
        "post_id": "rent_007",
        "title": "低预算软装让出租屋变温柔",
        "cover_text": "300元氛围感改造",
        "content": "只换床品、灯泡、桌布和画芯，保留原家具，搬家时也都能带走。",
        "tags": ["软装", "低预算", "出租屋"],
        "author": "温柔房间计划",
        "save_date": "2026-04-27",
        "last_viewed_date": "2026-05-08",
        "view_after_save_count": 5,
        "theme": "租房/小空间改造",
        "subtopics": ["低预算软装"],
        "ai_summary": "偏向情绪价值和生活感，适合作为改造第二步。",
        "memory_phrases": ["300元", "床品", "灯泡", "画芯"],
    },
    {
        "post_id": "rent_008",
        "title": "房东不让钉墙也能收纳",
        "cover_text": "免钉挂钩实测",
        "content": "对比了免钉胶、无痕钉和真空吸盘，轻物可以用免钉胶，重物建议落地架更稳。",
        "tags": ["免钉胶", "避坑", "不打孔"],
        "author": "租房避坑局",
        "save_date": "2026-04-29",
        "last_viewed_date": "2026-05-09",
        "view_after_save_count": 8,
        "theme": "租房/小空间改造",
        "subtopics": ["不打孔上墙", "出租屋避坑"],
        "ai_summary": "提醒免钉方案有承重边界，重物优先选择落地方案。",
        "memory_phrases": ["免钉胶", "无痕钉", "承重", "落地架"],
    },
    {
        "post_id": "rent_009",
        "title": "这几个角落真的别浪费",
        "cover_text": "夹缝、床边、门后",
        "content": "冰箱旁夹缝柜、床边窄推车、门后挂篮都能吃掉零碎物品，不用改造硬装。",
        "tags": ["夹缝收纳", "门后收纳", "小户型"],
        "author": "角落改造师",
        "save_date": "2026-04-30",
        "last_viewed_date": "2026-05-06",
        "view_after_save_count": 4,
        "theme": "租房/小空间改造",
        "subtopics": ["不打孔上墙", "床底收纳"],
        "ai_summary": "利用非主空间收纳杂物，适合不想大动干戈的租房场景。",
        "memory_phrases": ["夹缝柜", "窄推车", "门后挂篮"],
    },
    {
        "post_id": "rent_010",
        "title": "窗边30cm也能做工位",
        "cover_text": "折叠桌 + 窄书架",
        "content": "窗边用壁靠折叠桌、窄书架和夹灯，白天办公晚上收起，不影响走动。",
        "tags": ["小空间工位", "折叠桌", "窗边"],
        "author": "下班后也要学习",
        "save_date": "2026-05-01",
        "last_viewed_date": "2026-05-09",
        "view_after_save_count": 6,
        "theme": "租房/小空间改造",
        "subtopics": ["小空间工位", "低预算软装"],
        "ai_summary": "适合把窗边窄空间转成临时学习和办公区域。",
        "memory_phrases": ["窗边30cm", "折叠桌", "窄书架", "夹灯"],
    },
    {
        "post_id": "rent_011",
        "title": "9㎡也能有客厅感",
        "cover_text": "地毯一铺就变了",
        "content": "用地毯划出休息区，床尾放小边几和落地灯，小房间也能有像客厅一样的角落。",
        "tags": ["9㎡", "软装", "出租屋"],
        "author": "小房间日记",
        "save_date": "2026-05-01",
        "last_viewed_date": "2026-05-10",
        "view_after_save_count": 4,
        "theme": "租房/小空间改造",
        "subtopics": ["低预算软装"],
        "ai_summary": "用软装分区制造生活感，不涉及硬装改造。",
        "memory_phrases": ["地毯", "床尾", "边几", "落地灯"],
    },
    {
        "post_id": "rent_012",
        "title": "出租屋卫生间别买错",
        "cover_text": "这些免钉件会掉",
        "content": "潮湿卫生间里免钉胶容易失效，浴室收纳优先用落地置物架和挂门架。",
        "tags": ["出租屋避坑", "卫生间收纳", "免钉"],
        "author": "租房少踩坑",
        "save_date": "2026-05-02",
        "last_viewed_date": "2026-05-10",
        "view_after_save_count": 10,
        "theme": "租房/小空间改造",
        "subtopics": ["出租屋避坑", "不打孔上墙"],
        "ai_summary": "对不打孔方案做风险提示，潮湿空间要避开弱粘贴。",
        "memory_phrases": ["卫生间", "免钉胶失效", "落地置物架"],
    },
    {
        "post_id": "rent_013",
        "title": "小推车到底放哪最顺手",
        "cover_text": "床边 / 厨房 / 洗衣机旁",
        "content": "小推车适合放在床边当床头柜、厨房放调料、洗衣机旁放洗衣液和脏衣篮。",
        "tags": ["小推车", "收纳", "洗衣机旁"],
        "author": "推车爱好者",
        "save_date": "2026-05-03",
        "last_viewed_date": "2026-05-09",
        "view_after_save_count": 5,
        "theme": "租房/小空间改造",
        "subtopics": ["洗衣机上方", "床底收纳"],
        "ai_summary": "移动收纳能兼容多场景，特别适合空间未定型的出租屋。",
        "memory_phrases": ["小推车", "床头柜", "洗衣液", "脏衣篮"],
    },
    {
        "post_id": "rent_014",
        "title": "洞洞板别乱买，先看这篇",
        "cover_text": "承重和安装方式",
        "content": "桌面洞洞板适合文具和护肤品，墙面洞洞板要看承重，租房建议选落地或夹桌款。",
        "tags": ["洞洞板", "不打孔", "桌面收纳"],
        "author": "收纳工具测评",
        "save_date": "2026-05-03",
        "last_viewed_date": "2026-05-11",
        "view_after_save_count": 7,
        "theme": "租房/小空间改造",
        "subtopics": ["不打孔上墙", "小空间工位", "出租屋避坑"],
        "ai_summary": "洞洞板适合轻物收纳，但租房要优先考虑可复原安装。",
        "memory_phrases": ["洞洞板", "护肤品", "夹桌款", "承重"],
    },
    {
        "post_id": "rent_015",
        "title": "洗衣机上面做护肤台，真香",
        "cover_text": "小卫生间也能放下",
        "content": "在洗衣机上方加窄层板和收纳盒，护肤品按早晚分层，吹风机挂在侧边。",
        "tags": ["洗衣机上方", "护肤台", "小卫生间"],
        "author": "早八也要精致",
        "save_date": "2026-05-04",
        "last_viewed_date": "2026-05-11",
        "view_after_save_count": 11,
        "theme": "租房/小空间改造",
        "subtopics": ["洗衣机上方", "不打孔上墙"],
        "ai_summary": "与洗衣机上方利用高度相关，也覆盖护肤台需求。",
        "memory_phrases": ["洗衣机上面", "护肤台", "窄层板", "吹风机"],
    },
    {
        "post_id": "rent_016",
        "title": "衣柜太小，我这样续命",
        "cover_text": "换季衣物藏起来",
        "content": "衣柜不够时，先把换季衣物压缩进床底，再用挂袋增加竖向容量。",
        "tags": ["衣柜收纳", "床底收纳", "换季"],
        "author": "衣柜整理中",
        "save_date": "2026-05-04",
        "last_viewed_date": "2026-05-10",
        "view_after_save_count": 3,
        "theme": "租房/小空间改造",
        "subtopics": ["床底收纳", "不打孔上墙"],
        "ai_summary": "把低频物品转移到床底，释放衣柜日常使用空间。",
        "memory_phrases": ["衣柜太小", "压缩袋", "床底", "挂袋"],
    },
    {
        "post_id": "rent_017",
        "title": "出租屋灯光一换，像搬了家",
        "cover_text": "别用惨白吸顶灯",
        "content": "用暖光灯泡、床头夹灯和落地灯，让出租屋夜晚更舒服，所有灯具都能搬走。",
        "tags": ["灯光", "软装", "出租屋"],
        "author": "灯光改造课代表",
        "save_date": "2026-05-05",
        "last_viewed_date": "2026-05-10",
        "view_after_save_count": 6,
        "theme": "租房/小空间改造",
        "subtopics": ["低预算软装", "小空间工位"],
        "ai_summary": "低成本提升生活感，尤其适合工作和睡眠氛围切换。",
        "memory_phrases": ["暖光灯泡", "夹灯", "落地灯", "搬走"],
    },
    {
        "post_id": "rent_018",
        "title": "折叠桌救了我的小卧室",
        "cover_text": "不用时收起来",
        "content": "小卧室无法放固定书桌，可以用折叠桌搭配可折叠椅，周末学习和平时化妆都够用。",
        "tags": ["折叠桌", "小空间工位", "出租屋"],
        "author": "临时工位也认真",
        "save_date": "2026-05-05",
        "last_viewed_date": "2026-05-11",
        "view_after_save_count": 8,
        "theme": "租房/小空间改造",
        "subtopics": ["小空间工位", "低预算软装"],
        "ai_summary": "折叠桌是高频行动建议，成本低且不占长期面积。",
        "memory_phrases": ["折叠桌", "可折叠椅", "学习", "化妆"],
    },
    {
        "post_id": "rent_019",
        "title": "门后挂起来，桌面空出来",
        "cover_text": "包包帽子都有家",
        "content": "门后挂架可以放包、帽子、围巾和次净衣，适合没有玄关的出租屋。",
        "tags": ["门后收纳", "不打孔", "出租屋"],
        "author": "门后一平米",
        "save_date": "2026-05-06",
        "last_viewed_date": "2026-05-10",
        "view_after_save_count": 4,
        "theme": "租房/小空间改造",
        "subtopics": ["不打孔上墙"],
        "ai_summary": "门后属于低成本垂直收纳，不伤墙且拿取方便。",
        "memory_phrases": ["门后挂架", "包包", "帽子", "次净衣"],
    },
    {
        "post_id": "rent_020",
        "title": "出租屋改造先别急着买",
        "cover_text": "三件最容易闲置",
        "content": "大地毯、重型墙架和尺寸不准的置物柜最容易踩坑，先量尺寸再买可退换款。",
        "tags": ["出租屋避坑", "低预算", "收纳"],
        "author": "买前冷静一下",
        "save_date": "2026-05-06",
        "last_viewed_date": "2026-05-11",
        "view_after_save_count": 9,
        "theme": "租房/小空间改造",
        "subtopics": ["出租屋避坑", "低预算软装"],
        "ai_summary": "提供购买前检查清单，避免低预算改造变成浪费。",
        "memory_phrases": ["大地毯", "重型墙架", "量尺寸", "可退换"],
    },
    {
        "post_id": "rent_021",
        "title": "床边20cm塞下我的全部杂物",
        "cover_text": "窄推车实测",
        "content": "20cm窄推车能放纸巾、充电器、睡前读物和护手霜，比床头柜更适合小卧室。",
        "tags": ["窄推车", "床边收纳", "小户型"],
        "author": "窄空间玩家",
        "save_date": "2026-05-07",
        "last_viewed_date": "2026-05-11",
        "view_after_save_count": 5,
        "theme": "租房/小空间改造",
        "subtopics": ["床底收纳", "低预算软装"],
        "ai_summary": "床边窄空间利用，适合替代笨重床头柜。",
        "memory_phrases": ["20cm", "窄推车", "纸巾", "充电器"],
    },
    {
        "post_id": "rent_022",
        "title": "阳台只有一米宽也别放弃",
        "cover_text": "洗衣 + 收纳 + 晾晒",
        "content": "洗衣机上方放伸缩架，侧面挂清洁工具，顶部用可折叠晾衣杆，让小阳台保持顺手。",
        "tags": ["阳台收纳", "洗衣机上方", "晾晒"],
        "author": "一米阳台计划",
        "save_date": "2026-05-07",
        "last_viewed_date": "2026-05-11",
        "view_after_save_count": 7,
        "theme": "租房/小空间改造",
        "subtopics": ["洗衣机上方", "不打孔上墙"],
        "ai_summary": "把洗衣机上方、侧边和顶部同时纳入收纳规划。",
        "memory_phrases": ["一米阳台", "伸缩架", "清洁工具", "晾衣杆"],
    },
    {
        "post_id": "rent_023",
        "title": "桌面洞洞板让我少找东西",
        "cover_text": "化妆品和文具分区",
        "content": "桌面洞洞板用来挂剪刀、数据线、发夹和小镜子，旁边放护肤收纳盒。",
        "tags": ["洞洞板", "小空间工位", "桌面收纳"],
        "author": "桌面终于清爽",
        "save_date": "2026-05-08",
        "last_viewed_date": "2026-05-11",
        "view_after_save_count": 4,
        "theme": "租房/小空间改造",
        "subtopics": ["小空间工位", "不打孔上墙"],
        "ai_summary": "适合桌面小物集中管理，也可联想到护肤台收纳。",
        "memory_phrases": ["桌面洞洞板", "数据线", "发夹", "护肤收纳盒"],
    },
    {
        "post_id": "rent_024",
        "title": "出租屋窗帘别买太厚",
        "cover_text": "显小还压抑",
        "content": "小房间更适合浅色窗帘和纱帘叠加，遮光帘只放睡眠区，视觉更轻。",
        "tags": ["窗帘", "软装", "小户型"],
        "author": "软装少花钱",
        "save_date": "2026-05-08",
        "last_viewed_date": "2026-05-10",
        "view_after_save_count": 3,
        "theme": "租房/小空间改造",
        "subtopics": ["低预算软装", "出租屋避坑"],
        "ai_summary": "通过轻量软装避免空间压迫感，适合小户型。",
        "memory_phrases": ["浅色窗帘", "纱帘", "遮光帘", "视觉更轻"],
    },
    {
        "post_id": "rent_025",
        "title": "厨房台面太小怎么活",
        "cover_text": "能上墙就上墙",
        "content": "调料用磁吸架和免钉置物架，砧板竖放，锅盖挂起来，台面只留常用电器。",
        "tags": ["厨房收纳", "不打孔", "小户型"],
        "author": "厨房三平米",
        "save_date": "2026-05-09",
        "last_viewed_date": "2026-05-11",
        "view_after_save_count": 6,
        "theme": "租房/小空间改造",
        "subtopics": ["不打孔上墙", "出租屋避坑"],
        "ai_summary": "厨房小空间的垂直收纳方案，注意承重和油污清洁。",
        "memory_phrases": ["磁吸架", "免钉置物架", "锅盖", "台面"],
    },
    {
        "post_id": "rent_026",
        "title": "出租屋床头没有插座怎么办",
        "cover_text": "延长线也要藏好",
        "content": "用带开关延长线、线槽和床边窄架整理电线，避免插线板直接堆在地上。",
        "tags": ["电线整理", "床边收纳", "出租屋"],
        "author": "电线看不见",
        "save_date": "2026-05-09",
        "last_viewed_date": "2026-05-11",
        "view_after_save_count": 5,
        "theme": "租房/小空间改造",
        "subtopics": ["床底收纳", "出租屋避坑"],
        "ai_summary": "解决床边用电和杂乱问题，属于行动前的安全整理。",
        "memory_phrases": ["延长线", "线槽", "插线板", "床边窄架"],
    },
    {
        "post_id": "rent_027",
        "title": "小房间配色别超过三种",
        "cover_text": "真的会显大一点",
        "content": "白色、浅木色和一点红色点缀就够了，收纳盒颜色统一后房间会更干净。",
        "tags": ["配色", "软装", "小房间"],
        "author": "配色不纠结",
        "save_date": "2026-05-10",
        "last_viewed_date": "2026-05-11",
        "view_after_save_count": 3,
        "theme": "租房/小空间改造",
        "subtopics": ["低预算软装"],
        "ai_summary": "用统一配色降低视觉杂乱，适合收纳完成后的氛围提升。",
        "memory_phrases": ["三种颜色", "浅木色", "红色点缀", "统一收纳盒"],
    },
    {
        "post_id": "rent_028",
        "title": "搬家前我会先拍这几个地方",
        "cover_text": "押金保卫战",
        "content": "入住前拍墙面、地板、门窗、家电和水槽细节，改造时尽量选择可复原方案。",
        "tags": ["出租屋避坑", "押金", "可复原"],
        "author": "押金要拿回",
        "save_date": "2026-05-10",
        "last_viewed_date": "2026-05-11",
        "view_after_save_count": 8,
        "theme": "租房/小空间改造",
        "subtopics": ["出租屋避坑"],
        "ai_summary": "提醒改造前记录房屋状态，保护押金并约束改造方式。",
        "memory_phrases": ["入住前拍照", "墙面", "家电", "可复原"],
    },
    {
        "post_id": "rent_029",
        "title": "床尾别空着，放这个刚好",
        "cover_text": "长凳 + 收纳箱",
        "content": "床尾放窄长凳，下面塞收纳箱，上面能放包和第二天要穿的衣服。",
        "tags": ["床尾收纳", "小户型", "收纳箱"],
        "author": "床尾一米",
        "save_date": "2026-05-10",
        "last_viewed_date": "2026-05-11",
        "view_after_save_count": 2,
        "theme": "租房/小空间改造",
        "subtopics": ["床底收纳", "低预算软装"],
        "ai_summary": "床尾区域可兼顾临时放置和隐藏收纳。",
        "memory_phrases": ["床尾", "窄长凳", "收纳箱", "次日衣服"],
    },
    {
        "post_id": "rent_030",
        "title": "小空间工位不用一步到位",
        "cover_text": "先解决坐得下",
        "content": "先买折叠桌和舒服的椅垫，再补充台灯、插线板和桌面收纳，别一开始就买大书桌。",
        "tags": ["小空间工位", "折叠桌", "避坑"],
        "author": "临时书桌计划",
        "save_date": "2026-05-11",
        "last_viewed_date": "2026-05-11",
        "view_after_save_count": 4,
        "theme": "租房/小空间改造",
        "subtopics": ["小空间工位", "出租屋避坑", "低预算软装"],
        "ai_summary": "行动建议里优先推荐折叠桌，避免固定大件占空间。",
        "memory_phrases": ["先解决坐得下", "折叠桌", "台灯", "别买大书桌"],
    },
    {
        "post_id": "rent_031",
        "title": "洗衣机旁边10cm也有用",
        "cover_text": "夹缝架放清洁用品",
        "content": "洗衣机旁边用10cm夹缝架，放洗衣凝珠、刷子和垃圾袋，上方再加收纳篮。",
        "tags": ["洗衣机上方", "夹缝收纳", "小户型"],
        "author": "夹缝也要用上",
        "save_date": "2026-05-11",
        "last_viewed_date": "2026-05-11",
        "view_after_save_count": 3,
        "theme": "租房/小空间改造",
        "subtopics": ["洗衣机上方", "出租屋避坑"],
        "ai_summary": "补充洗衣区侧边空间利用，适合窄阳台和小卫生间。",
        "memory_phrases": ["洗衣机旁边", "10cm", "夹缝架", "收纳篮"],
    },
    {
        "post_id": "rent_032",
        "title": "便宜收纳盒别买太多",
        "cover_text": "先量床底高度",
        "content": "床底收纳盒要先量床脚高度和抽拉方向，太高会塞不进去，太深又不好拿。",
        "tags": ["床底收纳", "出租屋避坑", "收纳盒"],
        "author": "量尺寸再下单",
        "save_date": "2026-05-11",
        "last_viewed_date": "2026-05-11",
        "view_after_save_count": 4,
        "theme": "租房/小空间改造",
        "subtopics": ["床底收纳", "出租屋避坑"],
        "ai_summary": "床底收纳前的尺寸提醒，避免买错收纳盒。",
        "memory_phrases": ["床底高度", "抽拉方向", "太高", "不好拿"],
    },
    {
        "post_id": "rent_033",
        "title": "没玄关的房间这样放包",
        "cover_text": "进门不再一地东西",
        "content": "用门后挂钩、窄鞋架和小托盘做临时玄关，钥匙、包和口罩都有固定位置。",
        "tags": ["不打孔", "门后收纳", "出租屋"],
        "author": "没有玄关也行",
        "save_date": "2026-05-11",
        "last_viewed_date": "2026-05-11",
        "view_after_save_count": 2,
        "theme": "租房/小空间改造",
        "subtopics": ["不打孔上墙", "低预算软装"],
        "ai_summary": "用门后和窄鞋架做低成本入户区，减少随手乱放。",
        "memory_phrases": ["门后挂钩", "窄鞋架", "小托盘", "临时玄关"],
    },
    {
        "post_id": "rent_034",
        "title": "床和墙之间这条缝别浪费",
        "cover_text": "书和充电器都有地方",
        "content": "床侧夹缝可以放超窄置物架，收纳书、眼罩、充电器和遥控器，比堆在床上舒服。",
        "tags": ["床边收纳", "夹缝收纳", "小户型"],
        "author": "床边不乱了",
        "save_date": "2026-05-11",
        "last_viewed_date": "2026-05-11",
        "view_after_save_count": 5,
        "theme": "租房/小空间改造",
        "subtopics": ["床底收纳", "低预算软装"],
        "ai_summary": "床侧夹缝是容易被忽略的低成本收纳点。",
        "memory_phrases": ["床侧夹缝", "超窄置物架", "充电器", "遥控器"],
    },
    {
        "post_id": "rent_035",
        "title": "小桌子也能有完整工位",
        "cover_text": "插线板藏到桌下",
        "content": "小桌面只保留电脑和台灯，文具上洞洞板，插线板用理线盒放到桌下。",
        "tags": ["小空间工位", "洞洞板", "理线"],
        "author": "桌面清空计划",
        "save_date": "2026-05-11",
        "last_viewed_date": "2026-05-11",
        "view_after_save_count": 4,
        "theme": "租房/小空间改造",
        "subtopics": ["小空间工位", "不打孔上墙"],
        "ai_summary": "小工位的重点是减少桌面占用，把轻物转移到垂直收纳。",
        "memory_phrases": ["小桌子", "电脑", "台灯", "理线盒"],
    },
    {
        "post_id": "rent_036",
        "title": "出租屋地毯我只推荐小块",
        "cover_text": "好洗才会一直用",
        "content": "小房间选床边小地毯或可机洗地垫，比大面积地毯更容易清洁和搬走。",
        "tags": ["低预算软装", "出租屋避坑", "地毯"],
        "author": "软装实用派",
        "save_date": "2026-05-11",
        "last_viewed_date": "2026-05-11",
        "view_after_save_count": 2,
        "theme": "租房/小空间改造",
        "subtopics": ["低预算软装", "出租屋避坑"],
        "ai_summary": "软装选择强调可清洁、可带走，避免大件闲置。",
        "memory_phrases": ["小块地毯", "可机洗", "容易清洁", "搬走"],
    },
    {
        "post_id": "rent_037",
        "title": "洗手台太小就往上找空间",
        "cover_text": "镜柜和侧边挂架",
        "content": "洗手台台面小，可以用镜柜、侧边免钉挂架和分层托盘，把护肤品和吹风机放上去。",
        "tags": ["洗衣机上方", "不打孔", "护肤台"],
        "author": "小卫生间自救",
        "save_date": "2026-05-11",
        "last_viewed_date": "2026-05-11",
        "view_after_save_count": 6,
        "theme": "租房/小空间改造",
        "subtopics": ["洗衣机上方", "不打孔上墙"],
        "ai_summary": "与洗衣机上方同属卫生间垂直收纳，可解决护肤台空间不足。",
        "memory_phrases": ["洗手台", "镜柜", "免钉挂架", "护肤品"],
    },
    {
        "post_id": "beauty_001",
        "title": "空瓶了才敢说的修护精华",
        "cover_text": "敏感肌春夏记录",
        "content": "记录三款修护精华的肤感、保湿度和后续搓泥情况。",
        "tags": ["护肤测评", "敏感肌", "精华"],
        "author": "慢慢护肤",
        "save_date": "2026-04-12",
        "last_viewed_date": "2026-04-18",
        "view_after_save_count": 2,
        "theme": "护肤测评",
        "subtopics": ["修护", "敏感肌"],
        "ai_summary": "偏护肤测评，与租房改造无关。",
        "memory_phrases": ["修护精华", "敏感肌", "搓泥"],
    },
    {
        "post_id": "food_001",
        "title": "下班十分钟番茄肥牛饭",
        "cover_text": "真的不用开火很久",
        "content": "番茄、肥牛和米饭就能做一人食快手菜，适合工作日晚上。",
        "tags": ["快手菜", "一人食", "番茄肥牛"],
        "author": "今晚吃很快",
        "save_date": "2026-04-14",
        "last_viewed_date": "2026-04-20",
        "view_after_save_count": 1,
        "theme": "快手菜",
        "subtopics": ["一人食"],
        "ai_summary": "快手菜收藏，与空间改造无关。",
        "memory_phrases": ["十分钟", "番茄", "肥牛"],
    },
    {
        "post_id": "fashion_001",
        "title": "通勤衬衫别只会配西裤",
        "cover_text": "五套不费力穿搭",
        "content": "用牛仔裤、半裙和薄针织搭配衬衫，适合春夏通勤。",
        "tags": ["通勤穿搭", "衬衫", "春夏"],
        "author": "衣柜减法",
        "save_date": "2026-04-16",
        "last_viewed_date": "2026-04-25",
        "view_after_save_count": 2,
        "theme": "通勤穿搭",
        "subtopics": ["衬衫"],
        "ai_summary": "穿搭收藏，与租房改造无关。",
        "memory_phrases": ["衬衫", "西裤", "半裙"],
    },
    {
        "post_id": "study_001",
        "title": "考前7天别再重做整本题",
        "cover_text": "错题回看顺序",
        "content": "考前复习先回看高频错题，再整理公式和易混概念。",
        "tags": ["考前复习", "学习方法", "错题"],
        "author": "考试周自救",
        "save_date": "2026-04-18",
        "last_viewed_date": "2026-05-01",
        "view_after_save_count": 3,
        "theme": "学习经验",
        "subtopics": ["复习计划"],
        "ai_summary": "学习收藏，与租房改造无关。",
        "memory_phrases": ["考前7天", "错题", "公式"],
    },
    {
        "post_id": "city_001",
        "title": "周末探店这家咖啡还会再去",
        "cover_text": "安静 / 有插座 / 甜品不错",
        "content": "记录一家适合周末看书的咖啡店，座位宽，有插座，下午人会变多。",
        "tags": ["周末探店", "咖啡", "城市生活"],
        "author": "周末去哪儿",
        "save_date": "2026-04-19",
        "last_viewed_date": "2026-04-26",
        "view_after_save_count": 1,
        "theme": "周末探店",
        "subtopics": ["咖啡店"],
        "ai_summary": "探店收藏，与租房改造无关。",
        "memory_phrases": ["咖啡店", "插座", "甜品"],
    },
    {
        "post_id": "beauty_002",
        "title": "油皮夏天底妆别叠太厚",
        "cover_text": "持妆8小时记录",
        "content": "分享油皮夏天底妆步骤，重点是控油妆前和局部遮瑕。",
        "tags": ["底妆", "油皮", "护肤测评"],
        "author": "底妆观察员",
        "save_date": "2026-04-21",
        "last_viewed_date": "2026-04-28",
        "view_after_save_count": 2,
        "theme": "护肤测评",
        "subtopics": ["底妆"],
        "ai_summary": "美妆内容，不进入小空间主题收藏夹。",
        "memory_phrases": ["油皮", "底妆", "控油"],
    },
    {
        "post_id": "food_002",
        "title": "空气炸锅鸡翅不用腌一晚",
        "cover_text": "懒人版也入味",
        "content": "用生抽、蚝油和蒜粉快速腌制鸡翅，空气炸锅二十分钟。",
        "tags": ["空气炸锅", "快手菜", "鸡翅"],
        "author": "懒人厨房",
        "save_date": "2026-04-24",
        "last_viewed_date": "2026-05-02",
        "view_after_save_count": 1,
        "theme": "快手菜",
        "subtopics": ["空气炸锅"],
        "ai_summary": "食谱内容，不进入小空间主题收藏夹。",
        "memory_phrases": ["空气炸锅", "鸡翅", "二十分钟"],
    },
    {
        "post_id": "fashion_002",
        "title": "小个子通勤鞋我留了这三双",
        "cover_text": "能走路才重要",
        "content": "比较乐福鞋、低跟玛丽珍和轻便运动鞋的通勤舒适度。",
        "tags": ["通勤穿搭", "鞋子", "小个子"],
        "author": "每天都要走很多路",
        "save_date": "2026-04-27",
        "last_viewed_date": "2026-05-04",
        "view_after_save_count": 2,
        "theme": "通勤穿搭",
        "subtopics": ["鞋子"],
        "ai_summary": "穿搭内容，不进入小空间主题收藏夹。",
        "memory_phrases": ["乐福鞋", "玛丽珍", "运动鞋"],
    },
    {
        "post_id": "study_002",
        "title": "背单词别只盯着APP打卡",
        "cover_text": "复盘比数量重要",
        "content": "用错词本、例句复述和间隔复习提高记忆，不追求每天虚高数量。",
        "tags": ["学习方法", "背单词", "复盘"],
        "author": "语言学习慢慢来",
        "save_date": "2026-04-30",
        "last_viewed_date": "2026-05-05",
        "view_after_save_count": 2,
        "theme": "学习经验",
        "subtopics": ["背单词"],
        "ai_summary": "学习方法内容，不进入小空间主题收藏夹。",
        "memory_phrases": ["错词本", "例句", "间隔复习"],
    },
    {
        "post_id": "city_002",
        "title": "一个人看展也很舒服",
        "cover_text": "周末半日路线",
        "content": "分享展览路线、附近咖啡和晚饭选择，适合一个人慢慢逛。",
        "tags": ["周末探店", "看展", "城市生活"],
        "author": "一个人出门",
        "save_date": "2026-05-02",
        "last_viewed_date": "2026-05-07",
        "view_after_save_count": 1,
        "theme": "周末探店",
        "subtopics": ["看展"],
        "ai_summary": "生活方式内容，不进入小空间主题收藏夹。",
        "memory_phrases": ["看展", "咖啡", "晚饭"],
    },
]


DEFAULT_VISIBLE_IDS = [
    "rent_001",
    "rent_002",
    "beauty_001",
    "rent_003",
    "food_001",
    "rent_004",
    "rent_005",
    "fashion_001",
    "rent_006",
    "study_001",
    "rent_007",
    "city_001",
]


SUBTOPICS = [
    "全部",
    "床底收纳",
    "不打孔上墙",
    "小空间工位",
    "洗衣机上方",
    "低预算软装",
    "出租屋避坑",
]


def get_default_posts() -> list[dict]:
    """Return a mixed feed for the default favorites page."""
    indexed = {post["post_id"]: post for post in POSTS}
    return [indexed[post_id] for post_id in DEFAULT_VISIBLE_IDS]


def get_theme_posts() -> list[dict]:
    """Return posts that AI has grouped into the small-space theme."""
    return [post for post in POSTS if post["theme"] == "租房/小空间改造"]


def search_theme_posts(query: str) -> list[dict]:
    """Simple scripted fuzzy search over title, content, tags, and memory phrases."""
    if not query.strip():
        return []

    normalized = query.lower().replace("上面", "上方")
    synonyms = {
        "洗衣机": ["洗衣机", "阳台", "护肤台", "置物架", "洞洞板"],
        "上方": ["上方", "上面", "伸缩架", "置物架", "层板"],
        "利用": ["利用", "收纳", "空间", "放"],
        "床": ["床底", "床边", "床尾", "收纳箱"],
        "打孔": ["不打孔", "免钉", "无痕", "洞洞板"],
        "工位": ["工位", "折叠桌", "窗边", "书桌"],
    }
    tokens = set(normalized.replace("？", "").replace("?", "").split())
    for key, words in synonyms.items():
        if key in normalized:
            tokens.update(words)

    scored = []
    for post in get_theme_posts():
        haystack = " ".join(
            [
                post["title"],
                post["content"],
                " ".join(post["tags"]),
                " ".join(post["subtopics"]),
                " ".join(post["memory_phrases"]),
            ]
        ).lower()
        score = sum(1 for token in tokens if token and token.lower() in haystack)
        if score:
            scored.append((score, post))

    scored.sort(key=lambda item: (-item[0], item[1]["save_date"]))
    return [post for _, post in scored[:8]]
